package com.apple;

import cpp.objc.NSString;
import cpp.objc.NSDictionary;
import haxe.Int64;

@:objc
@:native("CALayer")
@:include("UIKit/UIKit.h")
extern class CALayer
implements cpp.objc.Protocol<NSCoding>
implements cpp.objc.Protocol<CAMediaTiming>
{
  @:native("setMasksToBounds") public function setMasksToBounds(masksToBounds:Dynamic /*Bool*/):Dynamic /*Void*/;
  @:native("needsDisplayOnBoundsChange") public function needsDisplayOnBoundsChange():Dynamic /*Bool*/;
  @:native("allowsGroupOpacity") public function allowsGroupOpacity():Dynamic /*Bool*/;
  @:native("anchorPointZ") public function anchorPointZ():Float;
  @:native("presentationLayer") public function presentationLayer():CALayer;
  @:native("masksToBounds") public function masksToBounds():Dynamic /*Bool*/;
  @:native("setOpacity") public function setOpacity(opacity:Dynamic /*Float*/):Dynamic /*Void*/;
  @:native("defaultValueForKey") public static function defaultValueForKey(key:NSString):Dynamic /*Dynamic*/;
  @:native("setContentsGravity") public function setContentsGravity(contentsGravity:NSString):Dynamic /*Void*/;
  @:native("layer") public static function layer():CALayer;
  @:native("setFrame") public function setFrame(frame:CGRect):Dynamic /*Void*/;
  @:native("removeFromSuperlayer") public function removeFromSuperlayer():Dynamic /*Void*/;
  @:native("setContentsRect") public function setContentsRect(contentsRect:CGRect):Dynamic /*Void*/;
  @:native("setBounds") public function setBounds(bounds:CGRect):Dynamic /*Void*/;
  @:native("setMinificationFilterBias") public function setMinificationFilterBias(minificationFilterBias:Dynamic /*Float*/):Dynamic /*Void*/;
  @:native("isDoubleSided") public function isDoubleSided():Dynamic /*Bool*/;
  @:native("setAnchorPointZ") public function setAnchorPointZ(anchorPointZ:Float):Dynamic /*Void*/;
  @:native("actions") public function actions():Dynamic /*Dynamic*/;
  @:native("mask") public function mask():CALayer;
  @:native("insertSublayer:above") public function insertSublayer_above(layer:CALayer, sibling:CALayer):Dynamic /*Void*/;
  @:native("setEdgeAntialiasingMask") public function setEdgeAntialiasingMask(edgeAntialiasingMask:CAEdgeAntialiasingMask):Dynamic /*Void*/;
  @:native("setRasterizationScale") public function setRasterizationScale(rasterizationScale:Float):Dynamic /*Void*/;
  @:native("layoutSublayers") public function layoutSublayers():Dynamic /*Void*/;
  @:native("setZPosition") public function setZPosition(zPosition:Float):Dynamic /*Void*/;
  @:native("anchorPoint") public function anchorPoint():CGPoint;
  @:native("setBackgroundFilters") public function setBackgroundFilters(backgroundFilters:NSArray):Dynamic /*Void*/;
  @:native("contentsScale") public function contentsScale():Float;
  @:native("zPosition") public function zPosition():Float;
  @:native("setFilters") public function setFilters(filters:NSArray):Dynamic /*Void*/;
  @:native("visibleRect") public function visibleRect():CGRect;
  @:native("defaultActionForKey") public static function defaultActionForKey(event:NSString):CAAction;
  @:native("frame") public function frame():CGRect;
  @:native("actionForKey") public function actionForKey(event:NSString):CAAction;
  @:native("setSublayerTransform") public function setSublayerTransform(sublayerTransform:CATransform3D):Dynamic /*Void*/;
  @:native("hitTest") public function hitTest(p:CGPoint):CALayer;
  @:native("autorelease") public function autorelease():CALayer;
  @:native("isHidden") public function isHidden():Dynamic /*Bool*/;
  @:native("sublayerTransform") public function sublayerTransform():CATransform3D;
  @:native("setDoubleSided") public function setDoubleSided(doubleSided:Dynamic /*Bool*/):Dynamic /*Void*/;
  @:native("isOpaque") public function isOpaque():Dynamic /*Bool*/;
  @:native("setContents") public function setContents(contents:Dynamic /*Dynamic*/):Dynamic /*Void*/;
  @:native("shadowColor") public function shadowColor():CGColor;
  @:native("setShadowOpacity") public function setShadowOpacity(shadowOpacity:Dynamic /*Float*/):Dynamic /*Void*/;
  @:native("setDrawsAsynchronously") public function setDrawsAsynchronously(drawsAsynchronously:Dynamic /*Bool*/):Dynamic /*Void*/;
  @:native("shadowRadius") public function shadowRadius():Float;
  @:native("insertSublayer:atIndex") public function insertSublayer_atIndex(layer:CALayer, idx:Dynamic /*Int*/):Dynamic /*Void*/;
  @:native("contentsAreFlipped") public function contentsAreFlipped():Dynamic /*Bool*/;
  @:native("delegate") public function delegate():CALayerDelegate;
  @:native("setContentsScale") public function setContentsScale(contentsScale:Float):Dynamic /*Void*/;
  @:native("convertTime:toLayer") public function convertTime_toLayer(t:Float, l:CALayer):Float;
  @:native("removeAllAnimations") public function removeAllAnimations():Dynamic /*Void*/;
  @:native("replaceSublayer:with") public function replaceSublayer_with(layer:CALayer, layer2:CALayer):Dynamic /*Void*/;
  @:native("setSublayers") public function setSublayers(sublayers:Dynamic /*Dynamic*/):Dynamic /*Void*/;
  @:native("minificationFilterBias") public function minificationFilterBias():Dynamic /*Float*/;
  @:native("borderColor") public function borderColor():CGColor;
  @:native("isGeometryFlipped") public function isGeometryFlipped():Dynamic /*Bool*/;
  @:native("setMinificationFilter") public function setMinificationFilter(minificationFilter:NSString):Dynamic /*Void*/;
  @:native("setShouldRasterize") public function setShouldRasterize(shouldRasterize:Dynamic /*Bool*/):Dynamic /*Void*/;
  @:native("layoutIfNeeded") public function layoutIfNeeded():Dynamic /*Void*/;
  @:native("animationKeys") public function animationKeys():Dynamic /*Dynamic*/;
  @:native("setAllowsGroupOpacity") public function setAllowsGroupOpacity(allowsGroupOpacity:Dynamic /*Bool*/):Dynamic /*Void*/;
  @:native("insertSublayer:below") public function insertSublayer_below(layer:CALayer, sibling:CALayer):Dynamic /*Void*/;
  @:native("addSublayer") public function addSublayer(layer:CALayer):Dynamic /*Void*/;
  @:native("setShadowOffset") public function setShadowOffset(shadowOffset:CGSize):Dynamic /*Void*/;
  @:native("setActions") public function setActions(actions:Dynamic /*Dynamic*/):Dynamic /*Void*/;
  @:native("renderInContext") public function renderInContext(ctx:CGContext):Dynamic /*Void*/;
  @:native("setHidden") public function setHidden(hidden:Dynamic /*Bool*/):Dynamic /*Void*/;
  @:native("alloc") public static function alloc():CALayer;
  @:native("backgroundColor") public function backgroundColor():CGColor;
  @:native("compositingFilter") public function compositingFilter():Dynamic /*Dynamic*/;
  @:native("initWithLayer") public function initWithLayer(layer:Dynamic /*Dynamic*/):CALayer;
  @:native("removeAnimationForKey") public function removeAnimationForKey(key:NSString):Dynamic /*Void*/;
  @:native("superlayer") public function superlayer():CALayer;
  @:native("scrollRectToVisible") public function scrollRectToVisible(r:CGRect):Dynamic /*Void*/;
  @:native("shouldRasterize") public function shouldRasterize():Dynamic /*Bool*/;
  @:native("setNeedsDisplay") public function setNeedsDisplay():Dynamic /*Void*/;
  @:native("bounds") public function bounds():CGRect;
  @:native("magnificationFilter") public function magnificationFilter():NSString;
  @:native("borderWidth") public function borderWidth():Float;
  @:native("preferredFrameSize") public function preferredFrameSize():CGSize;
  @:native("setDelegate") public function setDelegate(delegate:CALayerDelegate):Dynamic /*Void*/;
  @:native("convertPoint:fromLayer") public function convertPoint_fromLayer(p:CGPoint, l:CALayer):CGPoint;
  @:native("setCompositingFilter") public function setCompositingFilter(compositingFilter:Dynamic /*Dynamic*/):Dynamic /*Void*/;
  @:native("setContentsCenter") public function setContentsCenter(contentsCenter:CGRect):Dynamic /*Void*/;
  @:native("modelLayer") public function modelLayer():CALayer;
  @:native("transform") public function transform():CATransform3D;
  @:native("needsLayout") public function needsLayout():Dynamic /*Bool*/;
  @:native("setShadowColor") public function setShadowColor(shadowColor:CGColor):Dynamic /*Void*/;
  @:native("shadowOpacity") public function shadowOpacity():Dynamic /*Float*/;
  @:native("display") public function display():Dynamic /*Void*/;
  @:native("style") public function style():NSDictionary;
  @:native("setStyle") public function setStyle(style:NSDictionary):Dynamic /*Void*/;
  @:native("animationForKey") public function animationForKey(key:NSString):CAAnimation;
  @:native("setGeometryFlipped") public function setGeometryFlipped(geometryFlipped:Dynamic /*Bool*/):Dynamic /*Void*/;
  @:native("backgroundFilters") public function backgroundFilters():NSArray;
  @:native("shadowOffset") public function shadowOffset():CGSize;
  @:native("shouldArchiveValueForKey") public function shouldArchiveValueForKey(key:NSString):Dynamic /*Bool*/;
  @:native("setAllowsEdgeAntialiasing") public function setAllowsEdgeAntialiasing(allowsEdgeAntialiasing:Dynamic /*Bool*/):Dynamic /*Void*/;
  @:native("setCornerRadius") public function setCornerRadius(cornerRadius:Float):Dynamic /*Void*/;
  @:native("setNeedsLayout") public function setNeedsLayout():Dynamic /*Void*/;
  @:native("contentsFormat") public function contentsFormat():NSString;
  @:native("opacity") public function opacity():Dynamic /*Float*/;
  @:native("setShadowPath") public function setShadowPath(shadowPath:Dynamic):Dynamic /*Void*/;
  @:native("scrollPoint") public function scrollPoint(p:CGPoint):Dynamic /*Void*/;
  @:native("setAffineTransform") public function setAffineTransform(m:CGAffineTransform):Dynamic /*Void*/;
  @:native("setNeedsDisplayInRect") public function setNeedsDisplayInRect(r:CGRect):Dynamic /*Void*/;
  @:native("contentsGravity") public function contentsGravity():NSString;
  @:native("position") public function position():CGPoint;
  @:native("sublayers") public function sublayers():Dynamic /*Dynamic*/;
  @:native("addAnimation:forKey") public function addAnimation_forKey(anim:CAAnimation, key:NSString):Dynamic /*Void*/;
  @:native("setBackgroundColor") public function setBackgroundColor(backgroundColor:CGColor):Dynamic /*Void*/;
  @:native("convertRect:toLayer") public function convertRect_toLayer(r:CGRect, l:CALayer):CGRect;
  @:native("edgeAntialiasingMask") public function edgeAntialiasingMask():CAEdgeAntialiasingMask;
  @:native("setBorderColor") public function setBorderColor(borderColor:CGColor):Dynamic /*Void*/;
  @:native("drawInContext") public function drawInContext(ctx:CGContext):Dynamic /*Void*/;
  @:native("needsDisplayForKey") public static function needsDisplayForKey(key:NSString):Dynamic /*Bool*/;
  @:native("affineTransform") public function affineTransform():CGAffineTransform;
  @:native("contentsCenter") public function contentsCenter():CGRect;
  @:native("setName") public function setName(name:NSString):Dynamic /*Void*/;
  @:native("minificationFilter") public function minificationFilter():NSString;
  @:native("setOpaque") public function setOpaque(opaque:Dynamic /*Bool*/):Dynamic /*Void*/;
  @:native("setMask") public function setMask(mask:CALayer):Dynamic /*Void*/;
  @:native("convertTime:fromLayer") public function convertTime_fromLayer(t:Float, l:CALayer):Float;
  @:native("containsPoint") public function containsPoint(p:CGPoint):Dynamic /*Bool*/;
  @:native("allowsEdgeAntialiasing") public function allowsEdgeAntialiasing():Dynamic /*Bool*/;
  @:native("convertRect:fromLayer") public function convertRect_fromLayer(r:CGRect, l:CALayer):CGRect;
  @:native("setShadowRadius") public function setShadowRadius(shadowRadius:Float):Dynamic /*Void*/;
  @:native("setPosition") public function setPosition(position:CGPoint):Dynamic /*Void*/;
  @:native("filters") public function filters():NSArray;
  @:native("contents") public function contents():Dynamic /*Dynamic*/;
  @:native("name") public function name():NSString;
  @:native("setBorderWidth") public function setBorderWidth(borderWidth:Float):Dynamic /*Void*/;
  @:native("setAnchorPoint") public function setAnchorPoint(anchorPoint:CGPoint):Dynamic /*Void*/;
  @:native("setContentsFormat") public function setContentsFormat(contentsFormat:NSString):Dynamic /*Void*/;
  @:native("setNeedsDisplayOnBoundsChange") public function setNeedsDisplayOnBoundsChange(needsDisplayOnBoundsChange:Dynamic /*Bool*/):Dynamic /*Void*/;
  @:native("shadowPath") public function shadowPath():Dynamic;
  @:native("setTransform") public function setTransform(transform:CATransform3D):Dynamic /*Void*/;
  @:native("displayIfNeeded") public function displayIfNeeded():Dynamic /*Void*/;
  @:native("drawsAsynchronously") public function drawsAsynchronously():Dynamic /*Bool*/;
  @:native("needsDisplay") public function needsDisplay():Dynamic /*Bool*/;
  @:native("setMagnificationFilter") public function setMagnificationFilter(magnificationFilter:NSString):Dynamic /*Void*/;
  @:native("contentsRect") public function contentsRect():CGRect;
  @:native("convertPoint:toLayer") public function convertPoint_toLayer(p:CGPoint, l:CALayer):CGPoint;
  @:native("cornerRadius") public function cornerRadius():Float;
  @:native("rasterizationScale") public function rasterizationScale():Float;
  @:native("init") public function init():CALayer;
}
