package com.apple;

import cpp.objc.NSString;
import cpp.objc.NSDictionary;
import haxe.Int64;

@:objc
@:native("NSLayoutManager")
@:include("UIKit/UIKit.h")
extern class NSLayoutManager
implements cpp.objc.Protocol<NSCoding>
{
  @:native("getLineFragmentInsertionPointsForCharacterAtIndex:alternatePositions:inDisplayOrder:positions:characterIndexes") public function getLineFragmentInsertionPointsForCharacterAtIndex_alternatePositions_inDisplayOrder_positions_characterIndexes(charIndex:Int, aFlag:Dynamic /*Bool*/, dFlag:Dynamic /*Bool*/, positions:Float, charIndexes:Int):Int;
  @:native("invalidateDisplayForCharacterRange") public function invalidateDisplayForCharacterRange(charRange:Dynamic /*_NSRange*/):Dynamic /*Void*/;
  @:native("drawUnderlineForGlyphRange:underlineType:baselineOffset:lineFragmentRect:lineFragmentGlyphRange:containerOrigin") public function drawUnderlineForGlyphRange_underlineType_baselineOffset_lineFragmentRect_lineFragmentGlyphRange_containerOrigin(glyphRange:Dynamic /*_NSRange*/, underlineVal:NSUnderlineStyle, baselineOffset:Float, lineRect:CGRect, lineGlyphRange:Dynamic /*_NSRange*/, containerOrigin:CGPoint):Dynamic /*Void*/;
  @:native("setHyphenationFactor") public function setHyphenationFactor(hyphenationFactor:Float):Dynamic /*Void*/;
  @:native("textContainerForGlyphAtIndex:effectiveRange:withoutAdditionalLayout") public function textContainerForGlyphAtIndex_effectiveRange_withoutAdditionalLayout(glyphIndex:Int, effectiveGlyphRange:Dynamic /*_NSRange*/, flag:Dynamic /*Bool*/):NSTextContainer;
  @:native("setDrawsOutsideLineFragment:forGlyphAtIndex") public function setDrawsOutsideLineFragment_forGlyphAtIndex(flag:Dynamic /*Bool*/, glyphIndex:Int):Dynamic /*Void*/;
  @:native("characterRangeForGlyphRange:actualGlyphRange") public function characterRangeForGlyphRange_actualGlyphRange(glyphRange:Dynamic /*_NSRange*/, actualGlyphRange:Dynamic /*_NSRange*/):Dynamic /*_NSRange*/;
  @:native("isValidGlyphIndex") public function isValidGlyphIndex(glyphIndex:Int):Dynamic /*Bool*/;
  @:native("usedRectForTextContainer") public function usedRectForTextContainer(container:NSTextContainer):CGRect;
  @:native("setDelegate") public function setDelegate(delegate:NSLayoutManagerDelegate):Dynamic /*Void*/;
  @:native("setShowsInvisibleCharacters") public function setShowsInvisibleCharacters(showsInvisibleCharacters:Dynamic /*Bool*/):Dynamic /*Void*/;
  @:native("setUsesFontLeading") public function setUsesFontLeading(usesFontLeading:Dynamic /*Bool*/):Dynamic /*Void*/;
  @:native("hasNonContiguousLayout") public function hasNonContiguousLayout():Dynamic /*Bool*/;
  @:native("ensureLayoutForGlyphRange") public function ensureLayoutForGlyphRange(glyphRange:Dynamic /*_NSRange*/):Dynamic /*Void*/;
  @:native("notShownAttributeForGlyphAtIndex") public function notShownAttributeForGlyphAtIndex(glyphIndex:Int):Dynamic /*Bool*/;
  @:native("ensureGlyphsForCharacterRange") public function ensureGlyphsForCharacterRange(charRange:Dynamic /*_NSRange*/):Dynamic /*Void*/;
  @:native("getFirstUnlaidCharacterIndex:glyphIndex") public function getFirstUnlaidCharacterIndex_glyphIndex(charIndex:Int, glyphIndex:Int):Dynamic /*Void*/;
  @:native("extraLineFragmentRect") public function extraLineFragmentRect():CGRect;
  @:native("drawBackgroundForGlyphRange:atPoint") public function drawBackgroundForGlyphRange_atPoint(glyphsToShow:Dynamic /*_NSRange*/, origin:CGPoint):Dynamic /*Void*/;
  @:native("firstUnlaidGlyphIndex") public function firstUnlaidGlyphIndex():Int;
  @:native("drawStrikethroughForGlyphRange:strikethroughType:baselineOffset:lineFragmentRect:lineFragmentGlyphRange:containerOrigin") public function drawStrikethroughForGlyphRange_strikethroughType_baselineOffset_lineFragmentRect_lineFragmentGlyphRange_containerOrigin(glyphRange:Dynamic /*_NSRange*/, strikethroughVal:NSUnderlineStyle, baselineOffset:Float, lineRect:CGRect, lineGlyphRange:Dynamic /*_NSRange*/, containerOrigin:CGPoint):Dynamic /*Void*/;
  @:native("lineFragmentUsedRectForGlyphAtIndex:effectiveRange") public function lineFragmentUsedRectForGlyphAtIndex_effectiveRange(glyphIndex:Int, effectiveGlyphRange:Dynamic /*_NSRange*/):CGRect;
  @:native("textStorage") public function textStorage():NSTextStorage;
  @:native("strikethroughGlyphRange:strikethroughType:lineFragmentRect:lineFragmentGlyphRange:containerOrigin") public function strikethroughGlyphRange_strikethroughType_lineFragmentRect_lineFragmentGlyphRange_containerOrigin(glyphRange:Dynamic /*_NSRange*/, strikethroughVal:NSUnderlineStyle, lineRect:CGRect, lineGlyphRange:Dynamic /*_NSRange*/, containerOrigin:CGPoint):Dynamic /*Void*/;
  @:native("initWithCoder") public function initWithCoder(coder:NSCoder):NSLayoutManager;
  @:native("hyphenationFactor") public function hyphenationFactor():Float;
  @:native("invalidateDisplayForGlyphRange") public function invalidateDisplayForGlyphRange(glyphRange:Dynamic /*_NSRange*/):Dynamic /*Void*/;
  @:native("allowsNonContiguousLayout") public function allowsNonContiguousLayout():Dynamic /*Bool*/;
  @:native("insertTextContainer:atIndex") public function insertTextContainer_atIndex(container:NSTextContainer, index:Int):Dynamic /*Void*/;
  @:native("lineFragmentUsedRectForGlyphAtIndex:effectiveRange:withoutAdditionalLayout") public function lineFragmentUsedRectForGlyphAtIndex_effectiveRange_withoutAdditionalLayout(glyphIndex:Int, effectiveGlyphRange:Dynamic /*_NSRange*/, flag:Dynamic /*Bool*/):CGRect;
  @:native("glyphRangeForCharacterRange:actualCharacterRange") public function glyphRangeForCharacterRange_actualCharacterRange(charRange:Dynamic /*_NSRange*/, actualCharRange:Dynamic /*_NSRange*/):Dynamic /*_NSRange*/;
  @:native("invalidateGlyphsForCharacterRange:changeInLength:actualCharacterRange") public function invalidateGlyphsForCharacterRange_changeInLength_actualCharacterRange(charRange:Dynamic /*_NSRange*/, delta:Int, actualCharRange:Dynamic /*_NSRange*/):Dynamic /*Void*/;
  @:native("glyphRangeForBoundingRectWithoutAdditionalLayout:inTextContainer") public function glyphRangeForBoundingRectWithoutAdditionalLayout_inTextContainer(bounds:CGRect, container:NSTextContainer):Dynamic /*_NSRange*/;
  @:native("ensureGlyphsForGlyphRange") public function ensureGlyphsForGlyphRange(glyphRange:Dynamic /*_NSRange*/):Dynamic /*Void*/;
  @:native("glyphRangeForBoundingRect:inTextContainer") public function glyphRangeForBoundingRect_inTextContainer(bounds:CGRect, container:NSTextContainer):Dynamic /*_NSRange*/;
  @:native("characterIndexForPoint:inTextContainer:fractionOfDistanceBetweenInsertionPoints") public function characterIndexForPoint_inTextContainer_fractionOfDistanceBetweenInsertionPoints(point:CGPoint, container:NSTextContainer, partialFraction:Float):Int;
  @:native("textContainers") public function textContainers():Dynamic /*Dynamic*/;
  @:native("glyphAtIndex") public function glyphAtIndex(glyphIndex:Int):Int;
  @:native("autorelease") public function autorelease():NSLayoutManager;
  @:native("propertyForGlyphAtIndex") public function propertyForGlyphAtIndex(glyphIndex:Int):NSGlyphProperty;
  @:native("showsControlCharacters") public function showsControlCharacters():Dynamic /*Bool*/;
  @:native("setNotShownAttribute:forGlyphAtIndex") public function setNotShownAttribute_forGlyphAtIndex(flag:Dynamic /*Bool*/, glyphIndex:Int):Dynamic /*Void*/;
  @:native("firstUnlaidCharacterIndex") public function firstUnlaidCharacterIndex():Int;
  @:native("ensureLayoutForTextContainer") public function ensureLayoutForTextContainer(container:NSTextContainer):Dynamic /*Void*/;
  @:native("CGGlyphAtIndex:isValidIndex") public function CGGlyphAtIndex_isValidIndex(glyphIndex:Int, isValidIndex:Dynamic /*Bool*/):Int;
  @:native("characterIndexForGlyphAtIndex") public function characterIndexForGlyphAtIndex(glyphIndex:Int):Int;
  @:native("glyphAtIndex:isValidIndex") public function glyphAtIndex_isValidIndex(glyphIndex:Int, isValidIndex:Dynamic /*Bool*/):Int;
  @:native("setAttachmentSize:forGlyphRange") public function setAttachmentSize_forGlyphRange(attachmentSize:CGSize, glyphRange:Dynamic /*_NSRange*/):Dynamic /*Void*/;
  @:native("setGlyphs:properties:characterIndexes:font:forGlyphRange") public function setGlyphs_properties_characterIndexes_font_forGlyphRange(glyphs:Dynamic /*Dynamic*/, props:Dynamic /*Dynamic*/, charIndexes:Dynamic /*Dynamic*/, aFont:UIFont, glyphRange:Dynamic /*_NSRange*/):Dynamic /*Void*/;
  @:native("enumerateLineFragmentsForGlyphRange:usingBlock") public function enumerateLineFragmentsForGlyphRange_usingBlock(glyphRange:Dynamic /*_NSRange*/, block:Dynamic /*Dynamic*/):Dynamic /*Void*/;
  @:native("setExtraLineFragmentRect:usedRect:textContainer") public function setExtraLineFragmentRect_usedRect_textContainer(fragmentRect:CGRect, usedRect:CGRect, container:NSTextContainer):Dynamic /*Void*/;
  @:native("locationForGlyphAtIndex") public function locationForGlyphAtIndex(glyphIndex:Int):CGPoint;
  @:native("boundingRectForGlyphRange:inTextContainer") public function boundingRectForGlyphRange_inTextContainer(glyphRange:Dynamic /*_NSRange*/, container:NSTextContainer):CGRect;
  @:native("fractionOfDistanceThroughGlyphForPoint:inTextContainer") public function fractionOfDistanceThroughGlyphForPoint_inTextContainer(point:CGPoint, container:NSTextContainer):Float;
  @:native("delegate") public function delegate():NSLayoutManagerDelegate;
  @:native("ensureLayoutForBoundingRect:inTextContainer") public function ensureLayoutForBoundingRect_inTextContainer(bounds:CGRect, container:NSTextContainer):Dynamic /*Void*/;
  @:native("drawGlyphsForGlyphRange:atPoint") public function drawGlyphsForGlyphRange_atPoint(glyphsToShow:Dynamic /*_NSRange*/, origin:CGPoint):Dynamic /*Void*/;
  @:native("glyphIndexForCharacterAtIndex") public function glyphIndexForCharacterAtIndex(charIndex:Int):Int;
  @:native("setAllowsNonContiguousLayout") public function setAllowsNonContiguousLayout(allowsNonContiguousLayout:Dynamic /*Bool*/):Dynamic /*Void*/;
  @:native("textContainerForGlyphAtIndex:effectiveRange") public function textContainerForGlyphAtIndex_effectiveRange(glyphIndex:Int, effectiveGlyphRange:Dynamic /*_NSRange*/):NSTextContainer;
  @:native("setTextContainer:forGlyphRange") public function setTextContainer_forGlyphRange(container:NSTextContainer, glyphRange:Dynamic /*_NSRange*/):Dynamic /*Void*/;
  @:native("addTextContainer") public function addTextContainer(container:NSTextContainer):Dynamic /*Void*/;
  @:native("removeTextContainerAtIndex") public function removeTextContainerAtIndex(index:Int):Dynamic /*Void*/;
  @:native("ensureLayoutForCharacterRange") public function ensureLayoutForCharacterRange(charRange:Dynamic /*_NSRange*/):Dynamic /*Void*/;
  @:native("setLineFragmentRect:forGlyphRange:usedRect") public function setLineFragmentRect_forGlyphRange_usedRect(fragmentRect:CGRect, glyphRange:Dynamic /*_NSRange*/, usedRect:CGRect):Dynamic /*Void*/;
  @:native("showsInvisibleCharacters") public function showsInvisibleCharacters():Dynamic /*Bool*/;
  @:native("rangeOfNominallySpacedGlyphsContainingIndex") public function rangeOfNominallySpacedGlyphsContainingIndex(glyphIndex:Int):Dynamic /*_NSRange*/;
  @:native("showCGGlyphs:positions:count:font:matrix:attributes:inContext") public function showCGGlyphs_positions_count_font_matrix_attributes_inContext(glyphs:Dynamic /*Dynamic*/, positions:Dynamic /*Dynamic*/, glyphCount:Int, font:UIFont, textMatrix:CGAffineTransform, attributes:Dynamic /*Dynamic*/, graphicsContext:CGContext):Dynamic /*Void*/;
  @:native("getGlyphsInRange:glyphs:properties:characterIndexes:bidiLevels") public function getGlyphsInRange_glyphs_properties_characterIndexes_bidiLevels(glyphRange:Dynamic /*_NSRange*/, glyphBuffer:Int, props:NSGlyphProperty, charIndexBuffer:Int, bidiLevelBuffer:Dynamic /*Int*/):Int;
  @:native("lineFragmentRectForGlyphAtIndex:effectiveRange:withoutAdditionalLayout") public function lineFragmentRectForGlyphAtIndex_effectiveRange_withoutAdditionalLayout(glyphIndex:Int, effectiveGlyphRange:Dynamic /*_NSRange*/, flag:Dynamic /*Bool*/):CGRect;
  @:native("fillBackgroundRectArray:count:forCharacterRange:color") public function fillBackgroundRectArray_count_forCharacterRange_color(rectArray:Dynamic /*Dynamic*/, rectCount:Int, charRange:Dynamic /*_NSRange*/, color:UIColor):Dynamic /*Void*/;
  @:native("setLocation:forStartOfGlyphRange") public function setLocation_forStartOfGlyphRange(location:CGPoint, glyphRange:Dynamic /*_NSRange*/):Dynamic /*Void*/;
  @:native("lineFragmentRectForGlyphAtIndex:effectiveRange") public function lineFragmentRectForGlyphAtIndex_effectiveRange(glyphIndex:Int, effectiveGlyphRange:Dynamic /*_NSRange*/):CGRect;
  @:native("truncatedGlyphRangeInLineFragmentForGlyphAtIndex") public function truncatedGlyphRangeInLineFragmentForGlyphAtIndex(glyphIndex:Int):Dynamic /*_NSRange*/;
  @:native("enumerateEnclosingRectsForGlyphRange:withinSelectedGlyphRange:inTextContainer:usingBlock") public function enumerateEnclosingRectsForGlyphRange_withinSelectedGlyphRange_inTextContainer_usingBlock(glyphRange:Dynamic /*_NSRange*/, selectedRange:Dynamic /*_NSRange*/, textContainer:NSTextContainer, block:Dynamic /*Dynamic*/):Dynamic /*Void*/;
  @:native("setTextStorage") public function setTextStorage(textStorage:NSTextStorage):Dynamic /*Void*/;
  @:native("extraLineFragmentTextContainer") public function extraLineFragmentTextContainer():NSTextContainer;
  @:native("underlineGlyphRange:underlineType:lineFragmentRect:lineFragmentGlyphRange:containerOrigin") public function underlineGlyphRange_underlineType_lineFragmentRect_lineFragmentGlyphRange_containerOrigin(glyphRange:Dynamic /*_NSRange*/, underlineVal:NSUnderlineStyle, lineRect:CGRect, lineGlyphRange:Dynamic /*_NSRange*/, containerOrigin:CGPoint):Dynamic /*Void*/;
  @:native("setShowsControlCharacters") public function setShowsControlCharacters(showsControlCharacters:Dynamic /*Bool*/):Dynamic /*Void*/;
  @:native("textContainerChangedGeometry") public function textContainerChangedGeometry(container:NSTextContainer):Dynamic /*Void*/;
  @:native("glyphIndexForPoint:inTextContainer") public function glyphIndexForPoint_inTextContainer(point:CGPoint, container:NSTextContainer):Int;
  @:native("CGGlyphAtIndex") public function CGGlyphAtIndex(glyphIndex:Int):Int;
  @:native("glyphRangeForTextContainer") public function glyphRangeForTextContainer(container:NSTextContainer):Dynamic /*_NSRange*/;
  @:native("usesFontLeading") public function usesFontLeading():Dynamic /*Bool*/;
  @:native("drawsOutsideLineFragmentForGlyphAtIndex") public function drawsOutsideLineFragmentForGlyphAtIndex(glyphIndex:Int):Dynamic /*Bool*/;
  @:native("alloc") public static function alloc():NSLayoutManager;
  @:native("processEditingForTextStorage:edited:range:changeInLength:invalidatedRange") public function processEditingForTextStorage_edited_range_changeInLength_invalidatedRange(textStorage:NSTextStorage, editMask:NSTextStorageEditActions, newCharRange:Dynamic /*_NSRange*/, delta:Int, invalidatedCharRange:Dynamic /*_NSRange*/):Dynamic /*Void*/;
  @:native("glyphIndexForPoint:inTextContainer:fractionOfDistanceThroughGlyph") public function glyphIndexForPoint_inTextContainer_fractionOfDistanceThroughGlyph(point:CGPoint, container:NSTextContainer, partialFraction:Float):Int;
  @:native("numberOfGlyphs") public function numberOfGlyphs():Int;
  @:native("extraLineFragmentUsedRect") public function extraLineFragmentUsedRect():CGRect;
  @:native("init") public function init():NSLayoutManager;
  @:native("invalidateLayoutForCharacterRange:actualCharacterRange") public function invalidateLayoutForCharacterRange_actualCharacterRange(charRange:Dynamic /*_NSRange*/, actualCharRange:Dynamic /*_NSRange*/):Dynamic /*Void*/;
  @:native("attachmentSizeForGlyphAtIndex") public function attachmentSizeForGlyphAtIndex(glyphIndex:Int):CGSize;
}
