package com.apple;

import cpp.objc.NSString;
import cpp.objc.NSDictionary;
import haxe.Int64;

@:objc
@:native("UIViewController")
@:include("UIKit/UIKit.h")
extern class UIViewController
extends UIResponder
implements cpp.objc.Protocol<NSCoding>
implements cpp.objc.Protocol<UIAppearanceContainer>
implements cpp.objc.Protocol<UITraitEnvironment>
implements cpp.objc.Protocol<UIContentContainer>
implements cpp.objc.Protocol<UIFocusEnvironment>
implements cpp.objc.Protocol<UIStateRestoring>
implements cpp.objc.Protocol<NSExtensionRequestHandling>
{
  @:native("addChildViewController") public function addChildViewController(childController:UIViewController):Void;
  @:native("addKeyCommand") public function addKeyCommand(keyCommand:UIKeyCommand):Void;
  @:native("alloc") public static function alloc():UIViewController;
  @:native("allowedChildViewControllersForUnwindingFromSource") public function allowedChildViewControllersForUnwindingFromSource(source:UIStoryboardUnwindSegueSource):Dynamic;
  @:native("applicationFinishedRestoringState") public function applicationFinishedRestoringState():Void;
  @:native("attemptRotationToDeviceOrientation") public static function attemptRotationToDeviceOrientation():Void;
  @:native("automaticallyAdjustsScrollViewInsets") public function automaticallyAdjustsScrollViewInsets():Bool;
  @:native("automaticallyForwardAppearanceAndRotationMethodsToChildViewControllers") public function automaticallyForwardAppearanceAndRotationMethodsToChildViewControllers():Bool;
  @:overload(function():UIViewController {})
  @:native("autorelease") override public function autorelease():UIResponder;
  @:native("beginAppearanceTransition:animated") public function beginAppearanceTransition_animated(isAppearing:Bool, animated:Bool):Void;
  /* Implicit from NSExtensionRequestHandling */ @:native("beginRequestWithExtensionContext") public function beginRequestWithExtensionContext(context:NSExtensionContext):Void;
  @:native("bottomLayoutGuide") public function bottomLayoutGuide():UILayoutSupport;
  @:native("canPerformUnwindSegueAction:fromViewController:withSender") public function canPerformUnwindSegueAction_fromViewController_withSender(action:String, fromViewController:UIViewController, sender:Dynamic):Bool;
  @:native("childViewControllerContainingSegueSource") public function childViewControllerContainingSegueSource(source:UIStoryboardUnwindSegueSource):UIViewController;
  @:native("childViewControllerForStatusBarHidden") public function childViewControllerForStatusBarHidden():UIViewController;
  @:native("childViewControllerForStatusBarStyle") public function childViewControllerForStatusBarStyle():UIViewController;
  @:native("childViewControllers") public function childViewControllers():Dynamic;
  @:native("collapseSecondaryViewController:forSplitViewController") public function collapseSecondaryViewController_forSplitViewController(secondaryViewController:UIViewController, splitViewController:UISplitViewController):Void;
  @:native("contentSizeForViewInPopover") public function contentSizeForViewInPopover():CGSize;
  @:native("decodeRestorableStateWithCoder") public function decodeRestorableStateWithCoder(coder:NSCoder):Void;
  @:native("definesPresentationContext") public function definesPresentationContext():Bool;
  @:native("didAnimateFirstHalfOfRotationToInterfaceOrientation") public function didAnimateFirstHalfOfRotationToInterfaceOrientation(toInterfaceOrientation:UIInterfaceOrientation):Void;
  @:native("didMoveToParentViewController") public function didMoveToParentViewController(parent:UIViewController):Void;
  @:native("didReceiveMemoryWarning") public function didReceiveMemoryWarning():Void;
  @:native("didRotateFromInterfaceOrientation") public function didRotateFromInterfaceOrientation(fromInterfaceOrientation:UIInterfaceOrientation):Void;
  /* Implicit from UIFocusEnvironment */ @:native("didUpdateFocusInContext:withAnimationCoordinator") public function didUpdateFocusInContext_withAnimationCoordinator(context:UIFocusUpdateContext, coordinator:UIFocusAnimationCoordinator):Void;
  @:native("disablesAutomaticKeyboardDismissal") public function disablesAutomaticKeyboardDismissal():Bool;
  @:native("dismissModalViewControllerAnimated") public function dismissModalViewControllerAnimated(animated:Bool):Void;
  @:native("dismissViewControllerAnimated:completion") public function dismissViewControllerAnimated_completion(flag:Bool, completion:Dynamic):Void;
  @:native("edgesForExtendedLayout") public function edgesForExtendedLayout():UIRectEdge;
  @:native("editButtonItem") public function editButtonItem():UIBarButtonItem;
  @:native("encodeRestorableStateWithCoder") public function encodeRestorableStateWithCoder(coder:NSCoder):Void;
  /* Implicit from NSCoding */ @:native("encodeWithCoder") public function encodeWithCoder(aCoder:NSCoder):Void;
  @:native("endAppearanceTransition") public function endAppearanceTransition():Void;
  @:native("extendedLayoutIncludesOpaqueBars") public function extendedLayoutIncludesOpaqueBars():Bool;
  @:native("extensionContext") public function extensionContext():NSExtensionContext;
  @:native("hidesBottomBarWhenPushed") public function hidesBottomBarWhenPushed():Bool;
  @:native("initWithCoder") public function initWithCoder(aDecoder:NSCoder):UIViewController;
  @:native("initWithNibName:bundle") public function initWithNibName_bundle(nibNameOrNil:NSString, nibBundleOrNil:NSBundle):UIViewController;
  @:native("interfaceOrientation") public function interfaceOrientation():UIInterfaceOrientation;
  @:native("isBeingDismissed") public function isBeingDismissed():Bool;
  @:native("isBeingPresented") public function isBeingPresented():Bool;
  @:native("isEditing") public function isEditing():Bool;
  @:native("isModalInPopover") public function isModalInPopover():Bool;
  @:native("isMovingFromParentViewController") public function isMovingFromParentViewController():Bool;
  @:native("isMovingToParentViewController") public function isMovingToParentViewController():Bool;
  @:native("isViewLoaded") public function isViewLoaded():Bool;
  @:native("loadView") public function loadView():Void;
  @:native("loadViewIfNeeded") public function loadViewIfNeeded():Void;
  @:native("modalPresentationCapturesStatusBarAppearance") public function modalPresentationCapturesStatusBarAppearance():Bool;
  @:native("modalPresentationStyle") public function modalPresentationStyle():UIModalPresentationStyle;
  @:native("modalTransitionStyle") public function modalTransitionStyle():UIModalTransitionStyle;
  @:native("modalViewController") public function modalViewController():UIViewController;
  @:native("navigationController") public function navigationController():UINavigationController;
  @:native("navigationItem") public function navigationItem():UINavigationItem;
  @:native("nibBundle") public function nibBundle():NSBundle;
  @:native("nibName") public function nibName():NSString;
  /* Implicit from UIStateRestoring */ @:native("objectRestorationClass") public function objectRestorationClass():Dynamic /*Class<UIObjectRestoration>*/;
  @:native("overrideTraitCollectionForChildViewController") public function overrideTraitCollectionForChildViewController(childViewController:UIViewController):UITraitCollection;
  @:native("parentViewController") public function parentViewController():UIViewController;
  @:native("performSegueWithIdentifier:sender") public function performSegueWithIdentifier_sender(identifier:NSString, sender:Dynamic):Void;
  @:native("popoverPresentationController") public function popoverPresentationController():UIPopoverPresentationController;
  @:native("preferredContentSize") public function preferredContentSize():CGSize;
  /* Implicit from UIContentContainer */ @:native("preferredContentSizeDidChangeForChildContentContainer") public function preferredContentSizeDidChangeForChildContentContainer(container:UIContentContainer):Void;
  /* Implicit from UIFocusEnvironment */ @:native("preferredFocusEnvironments") public function preferredFocusEnvironments():Dynamic /*NSArray<id<UIFocusEnvironment>>*/;
  /* Implicit from UIFocusEnvironment */ @:native("preferredFocusedView") public function preferredFocusedView():UIView;
  @:native("preferredInterfaceOrientationForPresentation") public function preferredInterfaceOrientationForPresentation():UIInterfaceOrientation;
  @:native("preferredStatusBarStyle") public function preferredStatusBarStyle():UIStatusBarStyle;
  @:native("preferredStatusBarUpdateAnimation") public function preferredStatusBarUpdateAnimation():UIStatusBarAnimation;
  @:native("prefersStatusBarHidden") public function prefersStatusBarHidden():Bool;
  @:native("prepareForSegue:sender") public function prepareForSegue_sender(segue:UIStoryboardSegue, sender:Dynamic):Void;
  @:native("presentModalViewController:animated") public function presentModalViewController_animated(modalViewController:UIViewController, animated:Bool):Void;
  @:native("presentViewController:animated:completion") public function presentViewController_animated_completion(viewControllerToPresent:UIViewController, flag:Bool, completion:Dynamic):Void;
  @:native("presentationController") public function presentationController():UIPresentationController;
  @:native("presentedViewController") public function presentedViewController():UIViewController;
  @:native("presentingViewController") public function presentingViewController():UIViewController;
  @:native("previewActionItems") public function previewActionItems():Dynamic /*NSArray<id<UIPreviewActionItem>>*/;
  @:native("providesPresentationContextTransitionStyle") public function providesPresentationContextTransitionStyle():Bool;
  @:native("registerForPreviewingWithDelegate:sourceView") public function registerForPreviewingWithDelegate_sourceView(delegate:UIViewControllerPreviewingDelegate, sourceView:UIView):UIViewControllerPreviewing;
  @:native("removeFromParentViewController") public function removeFromParentViewController():Void;
  @:native("removeKeyCommand") public function removeKeyCommand(keyCommand:UIKeyCommand):Void;
  @:native("restorationClass") public function restorationClass():Dynamic /*Class<UIViewControllerRestoration>*/;
  @:native("restorationIdentifier") public function restorationIdentifier():NSString;
  /* Implicit from UIStateRestoring */ @:native("restorationParent") public function restorationParent():UIStateRestoring;
  @:native("restoresFocusAfterTransition") public function restoresFocusAfterTransition():Bool;
  @:native("rotatingFooterView") public function rotatingFooterView():UIView;
  @:native("rotatingHeaderView") public function rotatingHeaderView():UIView;
  @:native("searchDisplayController") public function searchDisplayController():UISearchDisplayController;
  @:native("segueForUnwindingToViewController:fromViewController:identifier") public function segueForUnwindingToViewController_fromViewController_identifier(toViewController:UIViewController, fromViewController:UIViewController, identifier:NSString):UIStoryboardSegue;
  @:native("separateSecondaryViewControllerForSplitViewController") public function separateSecondaryViewControllerForSplitViewController(splitViewController:UISplitViewController):UIViewController;
  @:native("setAutomaticallyAdjustsScrollViewInsets") public function setAutomaticallyAdjustsScrollViewInsets(automaticallyAdjustsScrollViewInsets:Bool):Void;
  @:native("setContentSizeForViewInPopover") public function setContentSizeForViewInPopover(contentSizeForViewInPopover:CGSize):Void;
  @:native("setDefinesPresentationContext") public function setDefinesPresentationContext(definesPresentationContext:Bool):Void;
  @:native("setDisablesAutomaticKeyboardDismissal") public function setDisablesAutomaticKeyboardDismissal(disablesAutomaticKeyboardDismissal:Bool):Void;
  @:native("setEdgesForExtendedLayout") public function setEdgesForExtendedLayout(edgesForExtendedLayout:UIRectEdge):Void;
  @:native("setEditing") public function setEditing(editing:Bool):Void;
  @:native("setEditing:animated") public function setEditing_animated(editing:Bool, animated:Bool):Void;
  @:native("setExtendedLayoutIncludesOpaqueBars") public function setExtendedLayoutIncludesOpaqueBars(extendedLayoutIncludesOpaqueBars:Bool):Void;
  @:native("setHidesBottomBarWhenPushed") public function setHidesBottomBarWhenPushed(hidesBottomBarWhenPushed:Bool):Void;
  @:native("setModalInPopover") public function setModalInPopover(modalInPopover:Bool):Void;
  @:native("setModalPresentationCapturesStatusBarAppearance") public function setModalPresentationCapturesStatusBarAppearance(modalPresentationCapturesStatusBarAppearance:Bool):Void;
  @:native("setModalPresentationStyle") public function setModalPresentationStyle(modalPresentationStyle:UIModalPresentationStyle):Void;
  @:native("setModalTransitionStyle") public function setModalTransitionStyle(modalTransitionStyle:UIModalTransitionStyle):Void;
  /* Implicit from UIFocusEnvironment */ @:native("setNeedsFocusUpdate") public function setNeedsFocusUpdate():Void;
  @:native("setNeedsStatusBarAppearanceUpdate") public function setNeedsStatusBarAppearanceUpdate():Void;
  @:native("setOverrideTraitCollection:forChildViewController") public function setOverrideTraitCollection_forChildViewController(collection:UITraitCollection, childViewController:UIViewController):Void;
  @:native("setPreferredContentSize") public function setPreferredContentSize(preferredContentSize:CGSize):Void;
  @:native("setProvidesPresentationContextTransitionStyle") public function setProvidesPresentationContextTransitionStyle(providesPresentationContextTransitionStyle:Bool):Void;
  @:native("setRestorationClass") public function setRestorationClass(restorationClass:Dynamic /*Class<UIViewControllerRestoration>*/):Void;
  @:native("setRestorationIdentifier") public function setRestorationIdentifier(restorationIdentifier:NSString):Void;
  @:native("setRestoresFocusAfterTransition") public function setRestoresFocusAfterTransition(restoresFocusAfterTransition:Bool):Void;
  @:native("setTabBarItem") public function setTabBarItem(tabBarItem:UITabBarItem):Void;
  @:native("setTitle") public function setTitle(title:NSString):Void;
  @:native("setToolbarItems") public function setToolbarItems(toolbarItems:Dynamic):Void;
  @:native("setToolbarItems:animated") public function setToolbarItems_animated(toolbarItems:Dynamic, animated:Bool):Void;
  @:native("setTransitioningDelegate") public function setTransitioningDelegate(transitioningDelegate:UIViewControllerTransitioningDelegate):Void;
  @:native("setView") public function setView(view:UIView):Void;
  @:native("setWantsFullScreenLayout") public function setWantsFullScreenLayout(wantsFullScreenLayout:Bool):Void;
  @:native("shouldAutomaticallyForwardAppearanceMethods") public function shouldAutomaticallyForwardAppearanceMethods():Bool;
  @:native("shouldAutomaticallyForwardRotationMethods") public function shouldAutomaticallyForwardRotationMethods():Bool;
  @:native("shouldAutorotate") public function shouldAutorotate():Bool;
  @:native("shouldAutorotateToInterfaceOrientation") public function shouldAutorotateToInterfaceOrientation(toInterfaceOrientation:UIInterfaceOrientation):Bool;
  @:native("shouldPerformSegueWithIdentifier:sender") public function shouldPerformSegueWithIdentifier_sender(identifier:NSString, sender:Dynamic):Bool;
  /* Implicit from UIFocusEnvironment */ @:native("shouldUpdateFocusInContext") public function shouldUpdateFocusInContext(context:UIFocusUpdateContext):Bool;
  @:native("showDetailViewController:sender") public function showDetailViewController_sender(vc:UIViewController, sender:Dynamic):Void;
  @:native("showViewController:sender") public function showViewController_sender(vc:UIViewController, sender:Dynamic):Void;
  /* Implicit from UIContentContainer */ @:native("sizeForChildContentContainer:withParentContainerSize") public function sizeForChildContentContainer_withParentContainerSize(container:UIContentContainer, parentSize:CGSize):CGSize;
  @:native("splitViewController") public function splitViewController():UISplitViewController;
  @:native("storyboard") public function storyboard():UIStoryboard;
  @:native("supportedInterfaceOrientations") public function supportedInterfaceOrientations():UIInterfaceOrientationMask;
  /* Implicit from UIContentContainer */ @:native("systemLayoutFittingSizeDidChangeForChildContentContainer") public function systemLayoutFittingSizeDidChangeForChildContentContainer(container:UIContentContainer):Void;
  @:native("tabBarController") public function tabBarController():UITabBarController;
  @:native("tabBarItem") public function tabBarItem():UITabBarItem;
  @:native("targetViewControllerForAction:sender") public function targetViewControllerForAction_sender(action:String, sender:Dynamic):UIViewController;
  @:native("title") public function title():NSString;
  @:native("toolbarItems") public function toolbarItems():Dynamic;
  @:native("topLayoutGuide") public function topLayoutGuide():UILayoutSupport;
  /* Implicit from UITraitEnvironment */ @:native("traitCollection") public function traitCollection():UITraitCollection;
  /* Implicit from UITraitEnvironment */ @:native("traitCollectionDidChange") public function traitCollectionDidChange(previousTraitCollection:UITraitCollection):Void;
  @:native("transitionCoordinator") public function transitionCoordinator():UIViewControllerTransitionCoordinator;
  @:native("transitionFromViewController:toViewController:duration:options:animations:completion") public function transitionFromViewController_toViewController_duration_options_animations_completion(fromViewController:UIViewController, toViewController:UIViewController, duration:Float, options:UIViewAnimationOptions, animations:Dynamic, completion:Dynamic):Void;
  @:native("transitioningDelegate") public function transitioningDelegate():UIViewControllerTransitioningDelegate;
  @:native("unregisterForPreviewingWithContext") public function unregisterForPreviewingWithContext(previewing:UIViewControllerPreviewing):Void;
  @:native("unwindForSegue:towardsViewController") public function unwindForSegue_towardsViewController(unwindSegue:UIStoryboardSegue, subsequentVC:UIViewController):Void;
  /* Implicit from UIFocusEnvironment */ @:native("updateFocusIfNeeded") public function updateFocusIfNeeded():Void;
  @:native("updateViewConstraints") public function updateViewConstraints():Void;
  @:native("view") public function view():UIView;
  @:native("viewControllerForUnwindSegueAction:fromViewController:withSender") public function viewControllerForUnwindSegueAction_fromViewController_withSender(action:String, fromViewController:UIViewController, sender:Dynamic):UIViewController;
  @:native("viewDidAppear") public function viewDidAppear(animated:Bool):Void;
  @:native("viewDidDisappear") public function viewDidDisappear(animated:Bool):Void;
  @:native("viewDidLayoutSubviews") public function viewDidLayoutSubviews():Void;
  @:native("viewDidLoad") public function viewDidLoad():Void;
  @:native("viewDidUnload") public function viewDidUnload():Void;
  @:native("viewIfLoaded") public function viewIfLoaded():UIView;
  @:native("viewWillAppear") public function viewWillAppear(animated:Bool):Void;
  @:native("viewWillDisappear") public function viewWillDisappear(animated:Bool):Void;
  @:native("viewWillLayoutSubviews") public function viewWillLayoutSubviews():Void;
  /* Implicit from UIContentContainer */ @:native("viewWillTransitionToSize:withTransitionCoordinator") public function viewWillTransitionToSize_withTransitionCoordinator(size:CGSize, coordinator:UIViewControllerTransitionCoordinator):Void;
  @:native("viewWillUnload") public function viewWillUnload():Void;
  @:native("wantsFullScreenLayout") public function wantsFullScreenLayout():Bool;
  @:native("willAnimateFirstHalfOfRotationToInterfaceOrientation:duration") public function willAnimateFirstHalfOfRotationToInterfaceOrientation_duration(toInterfaceOrientation:UIInterfaceOrientation, duration:Float):Void;
  @:native("willAnimateRotationToInterfaceOrientation:duration") public function willAnimateRotationToInterfaceOrientation_duration(toInterfaceOrientation:UIInterfaceOrientation, duration:Float):Void;
  @:native("willAnimateSecondHalfOfRotationFromInterfaceOrientation:duration") public function willAnimateSecondHalfOfRotationFromInterfaceOrientation_duration(fromInterfaceOrientation:UIInterfaceOrientation, duration:Float):Void;
  @:native("willMoveToParentViewController") public function willMoveToParentViewController(parent:UIViewController):Void;
  @:native("willRotateToInterfaceOrientation:duration") public function willRotateToInterfaceOrientation_duration(toInterfaceOrientation:UIInterfaceOrientation, duration:Float):Void;
  /* Implicit from UIContentContainer */ @:native("willTransitionToTraitCollection:withTransitionCoordinator") public function willTransitionToTraitCollection_withTransitionCoordinator(newCollection:UITraitCollection, coordinator:UIViewControllerTransitionCoordinator):Void;
}
